### ISSUE TITLE
TODO: Update to week 7 code lol

### ISSUE THREAD

**Issue by Bloopsdoob** [Bloopsdoob/Funkin-Champions#2]
- [ ]  Split up IconGrid, MenuCharacter, and Character Select images per-character
- [ ]  Make those work LOL
- [ ]  Note Splashes
- [ ]  New input system
- [ ]  Refactor options menu
- [ ]  Chart editor improvements
- [ ]  Un-hardcode character offsets
- [ ]  Main Menu improvements
- [ ]  Move around assets, make shit look cleaner
- [ ]  Make week 7 a real thing??? (maybe wait for the real deal)

**Comment by KrTeSeriesK** [comment]
cock and balls
